bin/heudiconv
otherwise call 
```
(venv-heudiconv)kodiweera@head1:/data/BIDS/heudiconv$ /data/BIDS/heudiconv/bin/heudiconv -d '/data/BIDS/prisma/MPRAGE_GRAPPA2_%s/*' -f /data/BIDS/heudiconv/heuristics/convertall.py -s 0005 -c dcm2niix -o /data/BIDS/prisma/output2 -b
```
was bugging out on us... this thing needs tests!
=> BF: defined outname_bids as early as possible to could be used + import again Node, Function before use

bin/heudiconv
"borrowed" from datalad ;)  thus initiated using some kind of lgr etc -- good things to come eventually I bet ;)
ah -- with this compare:
```shell
$> bin/heudiconv  -d /tmp -s S -c dcm2niix -f asd   
Traceback (most recent call last):
File "bin/heudiconv", line 623, in <module>
is_bids=args.bids)
File "bin/heudiconv", line 429, in convert_dicoms
sdir = dicom_dir_template % sid
TypeError: not all arguments converted during string formatting
```
to
```shell
$> bin/heudiconv --dbg -d /tmp -s S -c dcm2niix -f asd
Traceback (most recent call last):
File "bin/heudiconv", line 623, in <module>
is_bids=args.bids)
File "bin/heudiconv", line 429, in convert_dicoms
sdir = dicom_dir_template % sid
TypeError: not all arguments converted during string formatting
()
> …
```
=> added --dbg to cmdline to fall into interactive debugger in case of error

README.md, bin/heudiconv
This new format allows users to include both subject id and session in
the search expression. Session is optional.
Also, Atom automatically cleaned up some of the whitespace in the
README file.
=> Change how the expression used to find DICOM files is formatted.

bin/heudiconv, heuristics/uc_bids.py
It's not uncommon when scanning participants to have to re-run a scan due to motion/confusion/claustrophobia/etc. In these cases, our lab adds "XX" to the name of the folder containing DICOMS for the failed/incomplete scan. I've added a field to `dicominfo` (`dcm_dir_name`) to store this information so these scans can be easily excluded from conversion using `heudiconv`. 
Not sure what the policy is on adding new heuristics to the main repo, but I've included mine for now.
=> Add dcm_dir_name to dicominfo (+ uc_bids heuristic)

Makefile
make install was broken for me until I dropped this line from Makefile.
=> remove reference to non-existent path: examples/heuristics/

bin/heudiconv
since nipype's Dcm2niix interface defaults `bids_format` to True, there were sometimes problems with lists of json sidecars. This change explicitly sets this to False when not `is_bids`
=> fix: allow non-bids dcm2niix conversion

bin/heudiconv, tests/test_main.py
- assign metadata also to the ones under sessions
- n/a for empty values (as the bible says)
- correct time stamps per file
- having -ses_ suffix where applicable (BIDS manuscript also was fixed, validator works correctly)
- sanitize more fields in .json files (just in case)
=> BF: many fixes for _scans.tsv files

bin/heudiconv
Although its stored at different locations in the DICOM depending on scanner manufacturer I have found the sequence name to be useful for developing heuristics. Might be worth including...
=> Add sequence name to metadata extracted for heuristics

bin/heudiconv, heuristics/dbic_bids_validator.cfg, tests/test_main.py
- sort scans by datetime first before filename (Closes #95)
- makes .heudiconv/ a subdataset in case of using `--datalad`. So ppl could install dataset without all the heudiconv provenance (which all should be private/sensitive since might leak some unsafe original filenames)
- adjusted validator for dbic_bids layout (with .heudiconv and .datalad subdirectories... I wished bids_validator supported regexes?)
=> Sort scans, .heudiconv into subdataset in --datalad mode

bin/heudiconv, tests/test_heuristics.py, tests/test_main.py
It was resulting in ignoring umask etc, and making files non-readable by others where they should have been.  Now it should be more consistent and only make files not writable, and if making writeable only for levels where they are also readable.
While at it also marked a test to be skipped if there is no datalad
=> BF: do not chmod files using hardcoded mode number

heudiconv/cli/run.py, heudiconv/convert.py, heudiconv/info.py, heudiconv/utils.py, requirements.txt
* revert `anon_sid` default to `None` in `run.py`, but log `sid` in datalad message
* currently, setting `anon_sid` is superceeding the BIDS cleaned `sid`
* remove lingering dicom tempdir when running with `-c none`
* add pathlib as a requirement
=> BF: bidify sid and remove lingering dicom tempdirs

tests/utils.py
To help datalad folks in a blind fight against windmills of apache logs
trying to figure out some reasonable usage statistics
That url points to the same files as ///, just that apache logs then saved separately and there is otherwise no easy reliable way to tell which accesses come from CI platforms vs regular folks in the cloud(s)
=> RF: use http://datasets-tests.datalad.org instead of /// for a test

.gitignore, Dockerfile, heudiconv/bids.py, heudiconv/cli/run.py, heudiconv/convert.py, heudiconv/queue.py
* missing function imports
* moved some variables to their proper scope
* some pep8 fixes as well
=> fix: various fixes left over from refactor

heudiconv/cli/run.py
also I started to dislike the name "locator", so I am accepting suggestions.  
It is the path under output dir, which could be used to define a hierarchy of datasets, so in --datalad mode every level would become a super dataset.  in ReproIn heuristic we use "PI/StudentOrAssistant/Study" hierarchy.
=> Allow to override locator path from the cmdline

heudiconv/convert.py
The call to `Dcm2niix` was passing in `source_names`, which was essentially being treated as `source_dir` anyways under the hood.
=> fix: use source_dir instead

.travis.yml, heudiconv/bids.py, heudiconv/convert.py, heudiconv/heuristics/reproin.py
- allow/strip any leading CAPITALS followed by a column with the series/protocol name (see https://github.com/ReproNim/reproin/issues/14)
- consider `series_description` after `protocol_name` if it was not only empty, but didn't parse according to our spec (thus should "allow" for `protocol_name` to be a fancy "xnatDownload" as in https://github.com/ReproNim/reproin/issues/14)
=> WiP: ReproIn heuristic - support usecase from @mih et al.

heudiconv/bids.py, heudiconv/utils.py
Here is a demo
```bash
git clone https://github.com/datalad/example-dicom-functional.git 
git -C example-dicom-functional checkout 1block
heudiconv -s my1 -f reproin -o out -b -a anon -l '' --minmeta --file example-dicom-functional/dicoms
cp example-dicom-functional/events.tsv anon/sub-my1/func/sub-my1_task-oneback_run-01_events.tsv
chmod 444 anon/sub-my1/func/sub-my1_task-oneback_run-01_events.tsv
```
Spent summer outside, but now back to scanning: a structural for the same dataset and subject as above (and no, this is not a longitudinal dataset).
```bash
git clone https://github.com/datalad/example-dicom-structural.git
heudiconv -s my1 -f reproin -o out2 -b -a anon -l '' --minmeta --file example-dicom-structural/dicoms  
INFO: Running heudiconv version 0.5.dev1
INFO: Analyzing 384 …
```
=> Heudiconv needlessly radicalizes its users

heudiconv/external/dlad.py, heudiconv/external/tests/test_dlad.py, heudiconv/utils.py
- Fixes #205 
- Should also now work with datalad 0.10 (set_metadata is a generator there now)
- Ideally we should have got a helper to "Fixup" metadata setting in already set incorrectly datasets
=> BF+ENH: set dist-restrictions metadata correctly

heudiconv/bids.py
closes #116 
* enh: support for single magnitude acquisitions
=> fix: do not load phasediff until exists

README.md
Since heuristics were moved one level lower in commit b1b7b60d, two links in README had to be updated.
This is an absolutly minor change. Feel free to discard it if a rewrite of readme before next release is coming anyway.
=> Fix links to heuristcs in README.md

heudiconv/bids.py, tests/test_main.py
Closes #240 
generate  randstr's in _scans files deterministically based on the content of the DICOM header (UIDs) so it would be difficult if not impossible to guess that random string. That should make those _scans.tsv reproducible even if done from scratch
=> Make randstr field in _scans files deterministic

CHANGELOG.md, heudiconv/heuristics/reproin.py, heudiconv/heuristics/test_reproin.py
- allow for a space to be used as a separator within `locator`
- provide details while throwing error on detecting multiple session markers
above will be merged locally/pushed, here is the next change:
- Reproin: make __dups indexes be per series (by default, not tunable ATM)
TODO:
=> Few small fixes from using ReproIn @ DBIC

heudiconv/info.py
Some older neurodebian systems still have prior releases of nipype
=> BF: requires nipype at least 0.12 where Dcm2niix interface was added

heudiconv/bids.py, heudiconv/parser.py, heudiconv/utils.py
main goal is to fix https://github.com/nipy/heudiconv/issues/277
TODOs
- If so, we should somehow automagically clean up possibly existing wrong/rogue files from previous conversions.
- related question for bids-specification:  https://github.com/bids-standard/bids-specification/issues/102
=> BF: unique json fields

heudiconv/tests/test_utils.py, heudiconv/utils.py
We should really consider stripping that ugly beast of mine from the code since it might cause more trouble than gain.  But for now just fixed up the regex to avoid
=> Fixing up the abomination -- the regex to remove multiple spaces before numbers

heudiconv/cli/run.py, heudiconv/convert.py
Fixes #206 
* allow passing of an interface config through the use of `Nipype`'s `BaseInterface.__init__(from_file)`
=> enh: allow additional dcm2niix configuration

heudiconv/cli/run.py, heudiconv/dicoms.py, heudiconv/parser.py, heudiconv/queue.py, heudiconv/tests/test_queue.py
Closes #302.
Since this was forgotten/neglected after #87, re-enables support for SLURM submission.
`queue_conversion` was refactored to read command line arguments, and pass them to the SLURM call script. This will help with less maintenance as options are changed or added, with the trade-off of requiring a command-line submission.
`--sbargs` was renamed to `--queue-args` to allow for additional queue support down the line.
=> FIX: SLURM queue support

heudiconv/dicoms.py, heudiconv/tests/test_dicoms.py
Closes #291.
Fixes an issue where dcmstack output was not indexed properly (due to the change in https://github.com/moloney/dcmstack/commit/3815ea225e641af7c6c3a4c454b7dcd1bd2ede66). This "silent" error was avoided when using the `--minmeta` flag.
* `stack` is set as the first iterated item of dcmstack's `parse_and_stack()`
* Parameter `force` of `embed_nifti()` was removed and automatically applied within.
* Test for various uses of `embed_nifti()`
=> fix: embedding issue

CHANGELOG.md, heudiconv/convert.py
Otherwise, if outtype had nii.gz BEFORE dicom by the heuristic (or like it is done in our tests)
- embedding etc simply would be skipped altogether since those variables get reset!
also removed an unused variable
edit 1: trigger was -- I just couldn't figure out - why am I not getting into that embed_ call while running the tests?!!! ;-)
=> BF: convert - move out resetting of outname and scaninfo outside of the loop

Dockerfile
This update of dcm2niix pulls more fields out of GE dicoms.
=> update dcm2niix to v1.0.20181125

heudiconv/bids.py
Closes #336.
Avoids sorting BIDS *scans.tsv files by date if it is not available.
=> fix: avoid date sorting assumption

heudiconv/heuristics/reproin.py, heudiconv/heuristics/test_reproin.py
As discussed here [https://github.com/ReproNim/reproin/issues/32#issue-439932420]( https://github.com/ReproNim/reproin/issues/32#issue-439932420)
I modified the heuristics to remove the Philips WIP prefix and a substitution for (date) to {date} as session label.
The later will only work if heudiconv is called with --file ..., not if the -d flag is used.
=> Reproin fix for Philips 

heudiconv/utils.py
Did it within treat_infofile so we could include filename to be shared in the
WARNING message
Closes #341
=> ENH: do not blow hard if prettyfication of json fails - just store as json module stores it

heudiconv/convert.py
AFAIK a single echo time is not making it multi-echo, or does it?
I might go more through that code, so this PR will be evolving unless rapidly merged ;)
=> RF+BF: make code a bit more pythonic, and change comparison > 1 not >=1 for deciding multi-echo

docs/usage.rst, heudiconv/cli/run.py, heudiconv/convert.py, heudiconv/dicoms.py, heudiconv/tests/test_heuristics.py
This is useful in batch processing to prevent potential race
conditions. The batch processing example has also been
modified to use this flag.
See #340
=> Add --skiptop flag to prevent writing top level bids files

heudiconv/convert.py
This changes the `dcm2niix` outname from an erroneous substring to the heuristic prefix. Specifically, it will change the call from
```
dcm2niix -b y -f func ...
```
to
```
dcm2niix -b y -f /path/to/bids/sub-1/func/sub-1_task-blah_bold ...
```
=> fix: dcm2niix outname

heudiconv/external/dlad.py
To "disable" someone would need to precreate the dataset without --fake-dates.
=> RF: make  datalad use fake dates timeline (by default).

heudiconv/heuristics/reproin.py, heudiconv/heuristics/test_reproin.py
There is also internal small ReproIn RF to minimize code duplication for common
functionality.
This change might result in slightly different naming due to now enforced order
of _dir- to come before the leftover BIDS suffixes.  So if previously there were
some other BIDS _key-value pairs which we did not treat in ReproIn, and they
were listed BEFORE _dir- - they might now be added AFTER it.  Some subsequent
PR should probably add treatment for other BIDS _key's (e.g. _ce) and place them
in the order listed within BIDS specification
Closes #357 
Unfortunately I believe we do not have any phantom SE scan with _dir- to provide some basic integration test for this fix ATM.
=> BF: ReproIn - Support pipolar fieldmaps by providing them with _epi not _magnitude

heudiconv/convert.py
Fixing possible error on `convert.py`  on sorting `None`. Workaround is to return `[None] * len(res_files)` instead of `sorted([None] * len(res_files))` upon `else` condition.
=> Fixed possible TypeError on sorting None object

heudiconv/info.py
HeuDiConv requires the function nipype.utils.filemanip.which(), which first appears in nipype release 1.0.0
=> BF:Change nipype required version to >=1.0.0

heudiconv/convert.py
Closes #347. If the EchoNumber tag is missing from the sequence metadata, this will use the EchoTimes from the associated multi-echo files to determine echo number.
=> FIX: Determine multi-echo echo numbers from EchoTimes 

heudiconv/info.py
First checking whether we've already fixed this in nipype `master`.
Fixes #374 
Related nipy/nipype#3037
=> FIX: Blacklist nipype 1.2.1, 1.2.2 in Python 2.7 to avoid TraitError

heudiconv/info.py, setup.py
Got the currently supported versions from `.travis.yml`. This will advertise better and keep `pip > 9.0.0` from installing on unsupported Python installations.
Also added in some basic classifiers.
Inspired by going to comment on a PR and not knowing what language features I could assume.
=> MNT: Add Python support metadata to package

heudiconv/bids.py, heudiconv/tests/test_heuristics.py, heudiconv/tests/test_main.py
Generate optional json files to accompany required tsv (e.g. `participants.tsv` and `_scans.tsv`).
By generating this, BIDS validator won't throw warnings due to expecting accompanying json.
Related [BIDS spec](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#tabular-files)
Closes #318
=> Generate optional jsons

heudiconv/tests/test_utils.py, heudiconv/utils.py
fixes #378 
This change prints out what json file was invalid.
=> ENH: identify invalid json

heudiconv/convert.py
Closes #368. This solution will likely be overwritten by a larger refactor of how multi-volume data are handled, but in the meantime this should allow heudiconv to convert complex fMRI data.
=> ENH: Support multi-echo EPI phase data

heudiconv/bids.py
I have a dicom with empty strings for date and time fields, which generated a ValueError in bids.py . This PR allows heudiconv to catch the exception and continue, setting `acq_time=None`. This is my desired behavior, and I think it's what others would like to have happen as well.
=> BF: handle error if ContentDate and ContentTime are empty

heudiconv/cli/run.py
Makes explicit that the --dicom_dir_template argument will assign each tarball to a separate session and ignore the --ses flag if multiple are found
Fixes #383
=> DOC: Clarify tarball session handling

heudiconv/cli/run.py, heudiconv/tests/test_main.py
Eventually some generalization of https://github.com/ReproNim/reproman/pull/493
should become part of etelemetry, and thus avoiding redoing it here. Thus fix is
minimal
Closes #405
=> BF: fix logging string + move etelemetry under try/except

.travis.yml, heudiconv/convert.py, heudiconv/external/dlad.py, heudiconv/info.py, heudiconv/tests/test_main.py, heudiconv/tests/utils.py, heudiconv/utils.py, requirements.txt
0.12 series introduced a good number of API changes. To avoid per-version special handling, I am just boosting minimal requirement to be datalad 0.12.2.
I also dropped bothering with annex.thin setting since IMHO it did nothing really in a typical use case.
=> BF: use datalad 0.12, drop PY2, include workaround for dcmstack installation

heudiconv/heuristics/reproin.py
this fix is specific to python 3.x , see comment in the change
This is a resurrected #413
=> BF: case seqinfos into a list so entries could be modified if necessary

heudiconv/heuristics/reproin.py, heudiconv/heuristics/test_reproin.py
First commit in the series describes problem at large
For some data we cannot rely on reliable presence of consistent study_description
across scans.  That results in the necessity to duplicate the same protocols2fix
records for multiple (not known in advance) study descriptions (actually -- their
hashes, which makes it even more difficult).  But in the cases with custom
overloads of protocols2fix, it is desired to just provide global rewrite rules,
which could be applied to any collection since they did follow some convention.
Now, with an empty "hash", those rules would be applied last, i.e. after possible
study-specific fixups applied.
As part of the solution I removed preliminary check to skip a call to
fix_dbic_protocol altogether.  It should be better this way.
I also removed …
=> ReproIn: make specification of protocols2fix more flexible + do not bind fixup structs in func signatures

heudiconv/convert.py
=> Set the  field 'TaskName' in the json file for multiecho func data

heudiconv/utils.py
I modified the code per your recommendation and then rebased the repository so you don't get a noisy commit.
This allows heuristic modules names that conflict with existing module
names, such as using a heuristic module named "heudiconv.py"
=> search heuristic file path first

heudiconv/cli/run.py, heudiconv/tests/test_main.py
partially addresses last item in #173 - ideally should work without heuristic, but not ATM, so I will keep that issue open, but at least it should crash more informatively
=> ENH: Provide informative exception if command needs a heuristic to be specified

heudiconv/convert.py, heudiconv/dicoms.py, heudiconv/tests/test_dicoms.py, heudiconv/tests/utils.py
Follow up to #420 
- `embed_dicom_and_nifti_metadata` will not produce nifti file if that one doesn't exist yet . This functionality (hopefully) was not used for a while, and we should rely on dcm2niix for all such conversions
- it also changes how json's dumped by that function -- it will use the same `save_json` instead of ad-hoc `json.dump` call with `indent=3`.  So with this PR we would end up changing .json files formatting a bit, which could complicate regression testing, but I think consistency is worth it
- `@assert_cwd_unchanged` now can be used to assure that tests do not jump to some other directories, or force their return (note that if directory has symlinks in the path -- we would return to dereferenced path)
=> RF: embed_nifti -> embed_dicom_and_nifti_metadata  and not invoke it if min_meta

heudiconv/bids.py, heudiconv/utils.py
- `json_dumps_pretty` had it set to 2
- many invocations of `save_json` also had 2 set manually
- `embed_nifti` has its invocation of json.dumps still set to `3`, but when #432 is merged, it would just use `save_json` with defaults, thus go to 2 
Altogether, although it would change formatting for some files, I think we better make formatting more consistent sooner (i.e. now) than later.
=> RF+ENH: save_json - indent=2 by default

heudiconv/info.py, setup.py
Ran into it while testing neurodebian package for 0.8.0 -- ran into:
```
$> docker run -it --rm reproin-test-0.8.0:latest --help
Traceback (most recent call last):
File "/usr/bin/heudiconv", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
@_call_aside
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
ws.require(__requires__)
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", …
```
=> RF(+BF somewhat): remove no longer needed dependencies etc

docs/tutorials.rst
This PR adds four yet unmentioned tutorials to the User tutorial section of the docs:
- DataLad + HeuDiConv tutorial: http://www.repronim.org/coco2019-training/04-02-reproin/ 
- ReproIn conversion workflow: https://github.com/repronim/reproin#conversion
- slides from ReproNim Webinar: https://docs.google.com/presentation/d/14UNWQVY49c9Xc-7sj1FkoILXnt-wYjW404oqT-FtCW8/edit#slide=id.p  
- video from ReproNim Webinar: https://www.youtube.com/watch?v=j2SKX37-w4c&list=PLs3CA4ShM1DUX0nTMKfoB8Z6kdrZpByLa&index=5&t=0s
=> DOC: add more tutorials to the overview

heudiconv/dicoms.py
This fixes an error of `ERROR: Embedding failed: 'NoneType' object is not subscriptable`.
It looks like `embed_dicom_and_nifti_metadata` no longer returns a json and metadata, but the Node wrapping it in `embed_metadata_from_dicoms` still was expecting an output. This was getting caught inside the try/catch block, but caused it to skip the rest of the processing in `embed_metadata_from_dicoms`.
This patch just removes the outputs from the node, since it appears to be unused.
=> [BF] remove unassigned embedfunc outputs

heudiconv/bids.py, heudiconv/tests/test_heuristics.py, heudiconv/tests/test_main.py, heudiconv/tests/test_utils.py, heudiconv/utils.py
Closes #447.
Changes proposed:
- Keep sub-second timing information in ContentTime when compiling `acq_time` for scans.tsv files.
=> [ENH] Retain sub-second resolution in scans files

heudiconv/external/dlad.py, heudiconv/external/tests/test_dlad.py, heudiconv/info.py, heudiconv/tests/test_main.py, utils/test-compare-two-versions.sh
TODOs
- ~~restrict MAX version of datalad~~ decided to stay optimist! ;-)
Closes #463
=> BF: be compatible with datalad 0.13

heudiconv/bids.py, heudiconv/tests/test_main.py
Closes #450. 
Changes proposed:
- Change ContentTime to AcquisitionTime for acq_time field in scans file.
- Change ContentDate to AcquisitionDate for acq_time field in scans file.
=> ENH: Use AcquisitionTime for acq_time scans file field

README.rst, heudiconv/bids.py, heudiconv/cli/run.py, heudiconv/convert.py, heudiconv/due.py, heudiconv/heuristics/reproin.py, heudiconv/info.py
Individual commits might provide more info.  Here is a result of a sample run with duecredit enabled:
```
DueCredit Report:
- Flexible DICOM converter for organizing brain imaging data / heudiconv (v 0.8.0) [1]
- ReproIn heudiconv heuristic for turnkey conversion into BIDS / heudiconv.heuristics.reproin (v 0.8) [2]
- I/O library to access to common neuroimaging file formats / nibabel (v 3.0.1) [3]
- Scientific tools library / numpy (v 1.17.4) [4]
3 packages cited
1 module cited
0 functions cited
References
----------
[1] Halchenko, Y. et al., 2020. nipy/heudiconv v0.8.0.
[2] Visconti di Oleggio Castello, M. et al., 2020. ReproNim/reproin 0.6.0.
[3] Brett, M. et al., 2015. Nibabel 2.0.1.
[4] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient …
```
=> ENH: zenodo referencing in README.rst + support for ducredit for heudiconv and reproin

heudiconv/convert.py, heudiconv/tests/test_convert.py
Closes #476.
Changes proposed:
- Replace `rec-<magnitude|phase>` with `part-<mag|phase>` now that BIDS supports the `part` entity.
- Update associated test.
=> ENH: Replace rec entity with part entity for complex-valued data

heudiconv/bids.py
BIDS [specifies](https://bids-specification.readthedocs.io/en/v1.4.1/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fmri-task-information) that the `"CogAtlasID"` should be a [URI](https://bids-specification.readthedocs.io/en/v1.4.1/02-common-principles.html#uniform-resource-indicator).
Fixes #472
=> URI formatting of the default "TODO" value for "CogAtlasID"

heudiconv/info.py
=> BF: boost minimal require nipype to 1.2.3 to address missing bval/bvec values issue

heudiconv/convert.py, heudiconv/parser.py, heudiconv/utils.py
dcm2niix started to segfault whenever -f is too long https://github.com/rordenlab/dcm2niix/issues/465 .
And it feels that we abused -f wherever -o should have been used.
I have not looked though through history of changes if such use of -f
was warranted, but as I see that output_dir is not explicitly defined,
decided to just use that one instead.
Initial commit  resolved the dcm2niix segfault during heudiconv/tests/test_heuristics.py::test_scans_keys_reproin
when testing on my laptop, BUT resulted in test failures since now placing the files in the output directory copying to destination was not working since it was destination.  I added conditional in `safe_copyfile` (0f6abbf) but that was not sufficient and also made me wonder -- if placing already at the destination (or near) why don't …
=> BF: split prefix into path (if any) and provide only basename as prefix for dcm2niix invocation

heudiconv/dicoms.py, heudiconv/tests/test_main.py, heudiconv/utils.py
This commit adds the `"AcquisitionTime"` to the `seqinfo`, so that it is available for the heuristic classification.
**Use case:**
At least for Siemens scanners, for anatomical images (MPRAGE, TSE), when you select the images to be normalized (i.e., corrected for coil sensitivity bias), it allows the user to also save the original images, as a separated series. 
If that is selected, we will have two series of DICOM files corresponding to the same run, with the only difference being the intensity normalization. If we were to extract both series in a BIDS compliant way, we should probably use the label `rec-` to distinguish between them (e.g., `rec-normalized` vs. `rec-original`).
However, it seems like most BIDS Apps (e.g., [MRIQC](mriqc.readthedocs.io) and [fMRIPrep](fmriprep.org)) …
=> ENH: Adds "AcquisitionTime" to the `seqinfo`

heudiconv/tests/test_main.py
`_git_custom_command` is now replaced by `call_git` (https://github.com/datalad/datalad/pull/3791/)
=> Update datalad call in test_prepare_for_datalad

heudiconv/bids.py, heudiconv/parser.py
Originally issue reported on
https://neurostars.org/t/heudicov-permission-denied-bids-derivatives-mriqc/16543
where heudiconv would crash while trying to create an _events.tsv file under derivatives/mriqc.
heudiconv should not care to look anywhere besides immediate subject directories, even if people
place derivatives direcly in the dataset into which they are also converting their data into
(making YODA unhappy).
TODOs
=> ENH+BF: find_files to take list of topdirs, look for _bold only under  sub-* directories

heudiconv/main.py
main.workflow() crashes with a TypeError when logging the latest
version if "NO_ET" is in os.environ because etelemetry.get_project()
returns None.  Guard against this failure as well the KeyError that
would be triggered if get_project(), for whatever reason, returns a
dictionary without a "version" key.
=> BF: Don't fail if etelemetry.get_project returns None

heudiconv/bids.py, heudiconv/tests/test_main.py, heudiconv/utils.py
instead of exactly the same .json alongside every `_scans.tsv`.  See the 2nd commit (https://github.com/nipy/heudiconv/commit/864da69a3b1acc875da2429290984126dad34b18) for more motivation etc.
While at it also RF'ed `_canonical_dump` into a tiny `json_dumps`
causes only minor merge conflict for #482
=> RF/ENH: populate a singular scans.json at the top level of the bids dataset

heudiconv/bids.py, heudiconv/tests/test_utils.py, heudiconv/utils.py
just to blindly counteract the effect which likely to happen whenever
some per-subject process is converting (and just load/saving .json files)
while some other top level populate_aggregated_jsons calls out to json_load
to "harvest" known information.  There it should be safe to retry since
then anyways the last one to load/save those top level files will produce
the correct one.
Hopefully closes #516
=> BF(workaround): retry loading json multiple times

heudiconv/convert.py
=> BF: Fix the order of the 'echo' entity in the filename

heudiconv/parser.py
=> try a simple fix for wrongly ordered files in tar file

heudiconv/bids/schema.py
I just copied the code from [here](/cbinyu/heudiconv/blob/BIDSFile_helper/heudiconv/bids.py).
It still needs work.
I don't have time now and didn't want to hold #452
=> ENH: First version of the BIDSFile class

heudiconv/heuristics/reproin.py, heudiconv/tests/test_convert.py
Just copy pasted from the doc.  I am afraid it might not work out as is for everyone, but ATM I think it is better to have it than not ;-)  I also tested locally on a sample conversion that `heudiconv --dbg -f reproin --command populate-intended-for` worked out nicely (for a single subj/sess conversion).
=> ENH: specify POPULATE_INTENDED_FOR_OPTS within reproin following the doc

heudiconv/tests/anonymize_script.py, heudiconv/tests/test_main.py
Tests were failing for me locally since logging by default was above INFO, and
I had no python but python3.  Since we are operating in python3 realm ATM, I have
decided to just change the shebang accordingly.
Since PR is trivial, will merge it as soon as CI is happy
=> BF(TST): use caplog to control logging level, use python3 in shebang

heudiconv/cli/monitor.py, heudiconv/convert.py, heudiconv/heuristics/reproin.py, heudiconv/parser.py, heudiconv/queue.py, heudiconv/tests/test_heuristics.py
Primarily goal of this PR is to kick out a 0.11.0 release since we are already at v0.10.0-146-g0da0323 with a good number of merged PRs.  I was hoping to finish #544 but haven't yet, so another MINOR major ;) might follow not too far away. Not sure if git foo is correct but at large here are the following pull request merges (kick out low #ed since those are PRs into PRs)
```
(git)lena:~/proj/heudiconv/heudiconv-master[enh-release]git
$> git log --pretty=oneline --merges v0.10.0..origin/master | grep 'pull request' | nl
1	0da03238898426538b54160a731809f0de6cd04b Merge pull request #558 from nipy/gh-557
2	a1f63de34f23a3f6a2a750caaeb9631191988978 Merge pull request #547 from cbinyu/fix_echo_order_in_filename
3	772feeba1fe87d0bc84d85a9a07ce20344ef46c2 Merge pull request #555 from dbic/rf-3.7 …
```
=> Run codespell on some obvious typos

.dockerignore
Note: that implies that local .git/ better does not contain any sensitive data.  We should be building off github action fresh clone, should be safe AFAIK
Closes #516 
Marking for release so we get 0.11.1 with a docker image on the hub (hopefully)
=> Remove .git/ from .dockerignore so that versioning works while building docker image

dev-requirements.txt
marked for release since why not, there were a few merges etc
=> 0.9 of dcmstack was released, no need for github version

.github/dependabot.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/test.yml
We are currently using older versions of the updated GitHub Actions actions, and these older versions still use Node 12, [which is deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
This PR also configures Dependabot to create PRs updating workflows whenever a new version of a used action is released, as discussed in https://github.com/datalad/datalad-extensions/pull/105.
=> Update GitHub Actions action versions

heudiconv/heuristics/multires_7Tbold.py, heudiconv/tests/test_heuristics.py, heudiconv/tests/test_queue.py
If all good -- will be merged for a release
=> DOC: codespell fix a few typos in code comments

docs/conf.py
Otherwise we get
WARNING: conf value "version" should not be empty for EPUB3
which I believe is what errors out our build on RTD.
=> DOC: do provide short version for sphinx

.codespellrc, .github/workflows/codespell.yml, CHANGELOG.md, utils/test-compare-two-versions.sh
we had fixed done before but never had CI to alert on adding new typos
=> Provide codespell config and workflow

heudiconv/convert.py
Also adjusted docstring to note that now _task- can be used in many other modalities
❯ git grep -l -B4 -E 'task: (r|o)'
src/schema/README.md
src/schema/rules/files/raw/anat.yaml
src/schema/rules/files/raw/beh.yaml
src/schema/rules/files/raw/channels.yaml
src/schema/rules/files/raw/eeg.yaml
src/schema/rules/files/raw/func.yaml
src/schema/rules/files/raw/ieeg.yaml
src/schema/rules/files/raw/meg.yaml
src/schema/rules/files/raw/nirs.yaml
src/schema/rules/files/raw/pet.yaml
src/schema/rules/files/raw/task.yaml
and overall -- even if required for some modality (e.g. func) IMHO we should not redo bids-validator functionality here.  It should be validator to report oddities (may be we should bolt on integration with basic validation present in bidsschematools).
Closes #613
=> Do not issue warning if cannot parse _task entity

README.rst, docs/installation.rst
I think at large this is Closes #115
pushed to this PR another doc extension about containers etc Closes #241
=> Add HOWTO 101 section, with references to ReproIn to README.rst

heudiconv/tests/conftest.py
@yarikoptic as discussed on Tuesday. I tried a few different approaches, I think this is better than via a fixture since it ensures it will always be set throughout the test suite, without having to annotate individual tests.
=> Setting git author and email in test environment

.github/workflows/docker.yml, .github/workflows/release.yml
We had on docker hub
so we were building also there. In consultation with @asmacdo we decided to just build on github actions since we have more control/logging (yet to establish con/tinuous I guess for the archive).  So I have disabled building on docker hub, and tuned the workflow so we provide continuity here.
=> Docker images: tag also as "unstable", strip "v" prefix, and avoid building in non-release workflow for releases.

utils/anon-cmd
A simple bash script which would keep local ../.git/anon_sid_map.csv (assuming the script goes e.g. into code/ or some other subfolder like .heudiconv/), and could be used as anonymization script
=> Add a bash anon-cmd to be used to incrementally anonymize sids

heudiconv/bids.py, heudiconv/convert.py, heudiconv/tests/test_bids.py
extended #540 with tests and minor code refactoring.
As we accumulated good number of changes, marking for release with this PR. If all green etc -- will proceed with the release.
=> strip non-alphanumeric from session ids too

heudiconv/cli/monitor.py
The `py` library should not be used in modern code, and it's not even listed as dependency of heudiconv, so I don't believe the current code even works.
=> Replace py.path with pathlib

heudiconv/info.py, heudiconv/tests/test_heuristics.py, heudiconv/tests/test_main.py, heudiconv/tests/test_tarballs.py
heudiconv requires Python 3.7 or higher, so there is no need to use `six`.
=> Remove use of `six`

heudiconv/tests/test_dicoms.py
The `runner()` call in `test_private_csa_header` in `test_dicoms.py` did not specify an outdir, and so the test was creating files in the current directory, which is the repository root when testing locally with tox.  This PR fixes the test to instead write to a temporary directory.
=> Make `test_private_csa_header` test write to temp dir

.gitignore
One of the tests creates a `sample_nifti.json` file in the `heudiconv/tests/data/` directory, and this file needs to be in the same directory as some of the files that are already in the `data/` directory (and so creating it in a temp directory won't work).  This PR thus adds the file to `.gitignore` so that it will be ignored by Git.
=> Add `sample_nifti.json` to `.gitignore`

heudiconv/__init__.py, heudiconv/cli/run.py
Calling `logging.basicConfig()` when your library is imported is incredibly rude, as it infringes upon the importing code's ability to configure the logging itself.  The only time (if any) the `heudiconv` package should call `logging.basicConfig()` is in the `main()` function for a command-line entry point.
See also <https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library>.
=> Don't call `logging.basicConfig()` in `__init__.py`

heudiconv/dicoms.py
Python's tarfile is using a compression level of 9 by default (back to and including python 3.5): https://docs.python.org/3/library/tarfile.html#tarfile.open
We see cases where this leads to a large waste of cpu cycles with minimal gain as opposed to compress level 5 or even 1. 
Setting a global `compresslevel` variable makes it easy to override from our heuristics, keeping the default with minimal code impact.
=> ENH: set and expose global dicom compresslevel var

heudiconv/dicoms.py
=> Make an `embed_dicom_and_nifti_metadata()` annotation work on Python 3.7

heudiconv/dicoms.py
This has the added benefit that mypy will error if a callable with a different return type is passed as `custom_grouping`.
=> Declare `custom_grouping` return type instead of casting

heudiconv/heuristics/reproin.py
Aiming to fix #40
@cookpa @tsalo -- may be such approach would be sufficient (i.e. would not cause some disturbance as e.g. not saving DICOM tarballs correctly for T1w)?  Would you be so kind to try on your data?
edit: an alternative -- completely ignore/skip them
=> BF(?): make _setter images be taken as scouts - only DICOMs are saved

heudiconv/bids.py, heudiconv/dicoms.py, heudiconv/tests/test_utils.py, heudiconv/utils.py
I  think overall it closes #657 and should address the issue reported on https://neurostars.org/t/heudiconv-time-format-error/25806
=> Make .subsecond optional in BIDS/DICOM datetime entries

heudiconv/parser.py
=> Fix inconsistent behavior of existing session when using -d compared to --files option: raise an AssertionError instead of just a warning

paper.md
This PR updates the value for the date entry in the metadata of the `paper.md` file to prevent the compilation [error](https://github.com/openjournals/joss-reviews/issues/5626#issuecomment-1625085413) happening during the [JOSS review](https://github.com/openjournals/joss-reviews/issues/5626)
=> Fix metadata

heudiconv/bids.py
AFAIK there were no relevant to us breakages. So just boosting the version to seemingly be up to date with BIDS.
Closes #698
=> Boost claimed BIDS version to 1.8.0 from 1.4.1

heudiconv/main.py
It refactors how we do check and assertion now for mypy to stay quiet. Closes #707
=> Do not demand --files for all commands, even those which do not care about it (like populate-intended-for)

heudiconv/main.py
To avoid users confusion etc. Ref: https://github.com/nipy/heudiconv/issues/707#issuecomment-1738371656
=> Convert assertion into a warning that we would not use dicom dir tempate option

heudiconv/heuristics/reproin.py, heudiconv/heuristics/test_reproin.py
black modified some unrelated portion but it is minor
=> ReproIn: give an informative assertion message when multiple values are found

heudiconv/heuristics/example.py, heudiconv/parser.py, tox.ini
=> Ran pre-commit on everything, black decided to adjust some formatting

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/typing.yml, heudiconv/info.py, pyproject.toml
=> Drop Python 3.7 support

utils/sensor-dicoms
This catches the interrupted scans we've been encountering.
=> Reject "Missing images" in sensor-dicoms

heudiconv/external/dlad.py, heudiconv/external/tests/test_dlad.py
Currently all globbed files in the current tree get marked as sensitive which could overwrite previously removed metas (eg after defacing), it now filter file in the commit where converted files are added.
If one runs heudiconv on a branch, remove the metadata (eg after defacing) then remove that branch and then rerun the same conversion on the same dataset, it seems like the new files with same names inherit the absence of metadata from the previous files (from git-annex branch). This is unexpected as the git-annex hash should differ so `.met` file should not be picked-up, but there is some git-annex black magic going on here. The issue is that sensitive files do not get marked as non-sensitive.
=> datalad sensitive marking fixes

README.rst, docs/heuristics.rst, heudiconv/convert.py, heudiconv/dicoms.py, heudiconv/heuristics/convertall.py, heudiconv/heuristics/convertall_custom.py, heudiconv/parser.py, heudiconv/tests/test_dicoms.py, heudiconv/utils.py
Getting back to #333 (attn @bpinsard ) and recent #580 (attn @kcho) decided may be to add to the army of custom ad-hoc callbacks etc heuristics could provide.  So, WDYT if heuristic could provide `custom_seqinfo` callable (crude example is below in PR) where any information could be extracted from already loaded nibabel's dicom wrapper or just a full list of files for that sequence.  I think it would be a slightly better solution to #333 since would not *always* store potentially sensitive path in the extracted metadata record  and potentially could operate on already loaded DICOM metadata thus making it faster to extract extra metadata.
@bpinsard @kcho -- would smth like that work for your cases?
TODOs
=> Add support for a  custom seqinfo to extract from DICOMs any additional metadata desired for a heuristic

heudiconv/dicoms.py
https://github.com/nipy/heudiconv/pull/755 but with my commit added -- I was not allowed to tune that PR.
Closes #755 
attn @jennan
=> Handle cases where dates/times in DICOM are empty strings, not Nones (e.g. after some anonymization)

.github/workflows/lint.yml, CITATION.cff
The actual script is pushed to
https://github.com/nipy/heudiconv/blob/paper-joss/tools/paper-to-citationcff
which was ran and then record was tuned up.
edit: purpose - to satisfy JOSS requirement to have release with a matching list of authors. See https://github.com/openjournals/joss-reviews/issues/5839#issuecomment-2088474424 and there on
=> Add CITATION.cff based on JOSS paper.md 

CITATION.cff
Is important for JOSS paper requirements and hopefully would set license on zenodo instead of (default?) CC 4.0
=> Specify license in CITATION.cff

.github/workflows/lint.yml
This reverts commit dcff5666bd789f7b1eff1ec33a4952fdb87aa389.
As we no longer have CITATION.cff and this was causing linters to fail.
We also need to trigger yet another release since zenodo integration for some reason was off.
=> Revert "Add CITATION.cff validation to lint workflow"

.zenodo.json
Got
{
"errors": "Invalid value 01cwqze88::2P41EB019936."
}
So it does not like something about that value. Later
=> Remove grants from .zenodo.json for now

docs/heuristics.rst, heudiconv/bids.py, heudiconv/tests/test_bids.py
Addresses #767
Do not use mixed acq/task entity for matching method as implemented for CustomAcquisitionLabel
=> [ENH] add PlainAcquisitionLabel IntendedFor method

paper.md
As per https://joss.readthedocs.io/en/latest/paper.html#names and https://github.com/openjournals/joss-reviews/issues/5839#issuecomment-2207175596
This should create a correct crossref and CITATION file
=> [JOSS] FIX split names into given-names/surname/suffix

docs/container.rst, docs/custom-heuristic.rst, docs/index.rst, docs/quickstart.rst
fixes a few docs files for empty spaces.
=> run pre-commit on all files to avoid unrelated errors in other PRs.

heudiconv/heuristics/reproin.py
This stems from #770.
Changes proposed:
- Rename the `s` variable to `curr_seqinfo` in the ReproIn heuristic, for readability.
=> Rename s variable to curr_seqinfo in reproin heuristic

.github/workflows/test.yml
also to check what the current state is since in fresh runs for
- https://github.com/nipy/heudiconv/pull/753
by @bpinsard we start getting
```
_____________________ test_embed_dicom_and_nifti_metadata ______________________
/home/runner/work/heudiconv/heudiconv/heudiconv/tests/test_dicoms.py:57: in test_embed_dicom_and_nifti_metadata
embed_dicom_and_nifti_metadata(dcmfiles, out_prefix + ".nii.gz", infofile, None)
/home/runner/work/heudiconv/heudiconv/heudiconv/dicoms.py:659: in embed_dicom_and_nifti_metadata
stack = ds.parse_and_stack(dcmfiles, force=True).values()
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/dcmstack/dcmstack.py:1156: in parse_and_stack
results = parse_and_group(src_paths,
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/dcmstack/ …
```
=> Run tests weekly to ensure we are still good

heudiconv/parser.py
It is only reproin which provides such handling and in general there should really be no harm -- we already raise exception if subject id is not provided/degenerate, so shold be safe to just inform instead of WARN the user.
Closes #783
=> Just INFO not WARNING if heuristic is missing intotoids

heudiconv/dicoms.py, heudiconv/tests/test_dicoms.py
fixes #752 
- [ ] need shareable test data
=> extract sequence_name from PulseSequenceName on Siemens XA** data

heudiconv/dicoms.py, heudiconv/tests/test_dicoms.py, heudiconv/tests/utils.py
Follow up to
- #753 
triggered by desire to avoid "growing" duplication and wanting to avoid call outs to `wrapper_from_file` at the test module import time.
=> Refactor create_seqinfo tiny bit to avoid duplication and add logging; and in tests to reuse list of dicom paths

heudiconv/bids.py, heudiconv/dicoms.py, heudiconv/tests/test_utils.py, heudiconv/utils.py
addresses #777 
Adds capability to handle datetime stripping for all datetimes allowed in the dicom and bids standards.
=> timezone aware

heudiconv/convert.py
This should provide compatibility with prior versions
Closes #786
=> BF(workaround): if heuristic provided just a string and not list of types -- make it into a tuple

heudiconv/external/dlad.py, heudiconv/tests/test_regression.py
I introduced a regression in #739, and it was not flagged by the tests.
This PR fixes the glob pattern to properly flag the files as sensitive. 
This is critical as if any data management pipeline rely on heudiconv setting this metadata, then sensitive data might not be handled appropriately/exposed.
I added that feature to the regression test, as this already require datalad to download data.
@yarikoptic let me know if you prefer this test to be it in a separate function.
=> Fix assignment of sensitive git-annex metadata data via glob patterns (regression introduced by #739)

heudiconv/parser.py
Situation is complicated is that when extracting .zip shutil.unpack_archive would also pass it and would crash so we need to pass only when extracting tar.  And also that kwargs option  was added in 3.12, started to be enforced in 3.13 and in 3.14 would be required
=> Do specify filter="tar" when extracting tars

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/typing.yml, heudiconv/info.py
to avoid a bunch of enhanced dicoms issues, notably through dcmstack. 
eg. 
```
dcmstack.dcmmeta.InvalidExtensionError: The extension is not valid: Missing required base classification time
``` 
should be fixed.
=> Require nibabel >= 5.3.1 (fixes issues with enhanced DICOMs), and drop Python 3.8 support 

docs/heuristics.rst
I might be confused, but the docs say "Any files where this function returns True will be filtered out." and I am convinced that it is the opposite.
The filter_files is used in the reproin heuristic (where it always returns True), with this docstring: "Return True if a file should be kept, else False". This commit adjusts the docs to effectively state the same (it used to say the opposite).
The docstring in the heudiconv heuristic was right: filter_files is fed to `dicoms.py::group_dicoms_into_seqinfos()` as `file_filter`, where it is applied with built-in `filter()` to the to-be-processed file list; `filter()` yields items for which `function(item) == True`.
N.B. This change makes it clear that `filter_files` and `filter_dicom` have opposite logic. The latter is fed to …
=> DOC: fix the description of filter_files

heudiconv/convert.py, heudiconv/tests/test_convert.py
Weirdly XA60 data that I got recently started to produce bvals/bvecs files for SBRef from dcm2niix.
I don't know where the changes originates, so better filter more aggressively here, as the only files allowed to have such sidefiles are `_dwi`  suffixed ones.
=> remove bval bvecs files generated for SBRef on XA60/CMRR/dcm2niix

heudiconv/dicoms.py, heudiconv/heuristics/reproin.py
see https://github.com/nipy/nibabel/issues/1392#issuecomment-2508066687
Apparently some of the validation of the dicom triggers nibabel.nicom that crashes on ill-formed dicoms.
Moving the dicom filter a bit before, allow to easily filter these with the heuristics `filter_dicom`. 
I should not change anything to the results.
=> [ENH] filter dicoms earlier to avoid nibabel crash with XA ill-formed mutli-planar localizer dicoms
