nipy/heudiconv

bin/heudiconv

Make prov optional, turn it off by default.

---

bin/heudiconv

- added dcm2niix conversion option
- made converter flag required - removed default 'dcm2nii'

[WIP] dcm2niix option

---

README.md
bin/heudiconv
examples/heuristics/multires_7Tbold.py
examples/heuristics/studyforrest_phase2.py
heuristics/bids_no_ses.py
heuristics/bids_of_jan.py
heuristics/bids_with_ses.py
heuristics/convertall.py
heuristics/example.py

Just had a look at the beast.  I must say "it needs tests" ;-)  Please review since I did some code changes, and hopefully have done de-tabification correctly.
Would you happen to have some DICOMs, probably on phantoms which could be used to exercise those heuristics?  then we could establish all the travis etc 
@chrisfilo may be you have a better alternative already for DICOM -> BIDS we could use with our soon-to-come Siemens 3T? ;-)

BF+DOC+ENH: converted tabs, fixed use of some variables, some PEP8ing, typos

---

bin/heudiconv

enh: add command line option for sbatch arguments

---

README.md
bin/heudiconv

@satra we should also update the dicominfo columns in the readme, as there are now more

fix: change default, update readme

---

bin/heudiconv

* remove non-alphanumeric characters from subject name
* `sub-` should be added to output subject directory
* `TaskName` key to functional json
* use img.affine property

enh: make output more bids like

---

bin/heudiconv

fix: try/except catch ReferringPhysicianName field

---

Dockerfile

now that it outputs TotalReadoutTime

DOCKER: update dcm2niix version

---

Dockerfile
bin/heudiconv

fix: minmeta added to convert and assertion removed to enable numeric comparison

---

bin/heudiconv

Closes #81 
Disclaimer: not tested ;-/

BF: do not try to produce scans files if layout is not fully BIDS yet

---

Makefile
bin/heudiconv

#83 
Also allows opening of non part 10 compliant dicoms

fix: compatible with mac install

---

bin/heudiconv

Catches an AttributeError if there is no entry for PerformingPhysicianName in the dicom header.

Fix: #93 (Missing PerformingPhysicianName entry)

---

heudiconv/bids.py
heudiconv/cli/run.py
heudiconv/convert.py
heudiconv/dicoms.py
heudiconv/external/dlad.py
heudiconv/parser.py
heudiconv/utils.py

this PR addresses:
* missing headers in generated `dicominfo.txt`
* style of multiline imports
* slightly less cryptic study UID error message

MAINT: general housekeeping

---

heuristics/banda-bids.py
heuristics/bids_with_ses.py

update some bids heuristics to include subject folder

fix: update heuristics to new style

---

heudiconv/cli/run.py
heudiconv/convert.py
tests/test_heuristics.py
tests/test_main.py
tests/utils.py

ENH: nipype >= 1.0.0 compat fix, var for heuristics finding, etc 

---

heudiconv/convert.py

I think the two lines I modified are supposed to execute _inside_ loop, rather that at the end of the loop.  That is, execute for every "item", rather than just for the last one.

Fixed spaces problem

---

heudiconv/utils.py

ENH: reincarnate the paranoid test of a json tuned up with regular expressions

---

heudiconv/external/dlad.py
heudiconv/utils.py

Fixes #161 
Actual fix is tiny in 2514875db25a7c8a954af7166e5cd02d99a3ce27 , the rest is just icing

Use .repo.set_metadata to stay compatible with upcoming datalad 0.10

---

heudiconv/external/dcmstack.py

Should fix up testing failures encountered during #177 
We would need to kick out yet another bugfix release for that... hopefully the last one in dealing with pydicom changes... heh

BF: pydicom 1.0.2 provided custom exception while trying to import dicom

---

heudiconv/utils.py
tests/test_main.py
tests/test_utils.py
utils/test-compare-two-versions.sh

My whole approach there for "pretty printing" json is a hack and should be RFed away eventually whenever more reports would come in ;)
For now this should close #182

BF: do not remove all spaces after a number

---

heudiconv/convert.py

should be fix #196. With the original code all dicoms are fed to dcm2niix and not only one scan.

fix multiple conversion #196

---

Dockerfile
heudiconv/cli/run.py
heudiconv/convert.py
heudiconv/external/pydicom.py
tests/test_heuristics.py
utils/gen-docker-image.sh

Started out as `Dockerfile` fixes, evolved to showing heudiconv a little love
* update Dockerfile
* add `util/gen-docker-image.sh` to easily generate new images with neurodocker
* `--overwrite` should not reuse conversion table
* if no valid argument is passed - don't print cryptic message, show help instead
* try to import latest pydicom first (> 1.0)
Classes #210

fix: various small fixes

---

setup.py

Closes #222 
although it is up for a discussion if we would want to go that far ;-)

BF: workaround for elderly buggy python 2.7 exec

---

CHANGELOG.md
Dockerfile
heudiconv/info.py
utils/gen-docker-image.sh
utils/update_changes.sh

* updated changelog
* add util script to help future changelog generation
* bump version
@yarikoptic let's get everything in order to release for this coming Monday

rel: 0.5.1

---

heudiconv/info.py
requirements.txt

now that its been added to pypi

MAINT: add dcmstack to deps

---

heudiconv/convert.py

Only tested with a small sample.

Trying to solve issue #249.

---

CHANGELOG.md
LICENSE
heudiconv/bids.py
heudiconv/info.py
heudiconv/parser.py
heudiconv/utils.py
setup.py

If tests pass, I will release unless objections are expressed

v0.5.2 Release

---

README.md

Added tutorial from the Center for Reproducible Neuroscience blog

Add tutorial to README.md

---

Dockerfile

upgrade to v1.0.20190410 before next release

bump: dcm2niix to latest release

---

heudiconv/convert.py

As suggested by @mgxd in https://github.com/nipy/heudiconv/issues/144, adding PDT2 as a multiecho modality label... WIP, still testing the mod.

Add PDT2 as valid multi echo sequence type

---

heudiconv/convert.py
heudiconv/tests/test_main.py

BF: avoid cached heuristic discrepancies

---

heudiconv/cli/run.py

DOC: Quote {subject} in example usage and provide a note in description

---

heudiconv/heuristics/reproin.py

Some of these changes were originally part of #387, but I've split them off at @yarikoptic's request to prevent PR sprawl. This just fixes a set of linting issues and typos in the heuristic file.

[REF] Fix miscellaneous typos in ReproIn heuristic file

---

heudiconv/tests/test_queue.py

Fixes #393
Extended fix could include testing if SLURM is actually
usable ATM

BF: fix check for the sbatch (SLURM) not being available

---

CHANGELOG.md
dev-requirements.txt
docs/conf.py
docs/installation.rst
docs/usage.rst
heudiconv/info.py
heudiconv/tests/test_utils.py

Do not merge. Submitting for possible review and to check if docs building was not spoiled. I will merge/push locally
Fixes #392

v0.6.0 CHANGELOG etc

---

heudiconv/dicoms.py
heudiconv/tests/test_dicoms.py

Add stop_before_pixels to the rest of dicom reads

---

heudiconv/bids.py

If empty string, replace it with `N/A`.

BF: Make sure participant sex is not left empty in 'participants.tsv'

---

heudiconv/bids.py
heudiconv/tests/test_bids.py

Also initiated test_bids.py to finally start collecting testing of
BIDS specific logic we add
Closes #499

ENH+BF: consistent  n/a for age/sex, also handle ?M for months

---

heudiconv/tests/test_main.py

This reverts commit 6ff5a967de66f4d14f7adccc01af27c5ed206b32.

Revert "BF(TST): workaround for python 3.5"

---

.gitignore
heudiconv/__init__.py
heudiconv/info.py
pyproject.toml
setup.py

Make versioningit write version to file; make setup.py read version as fallback

---

setup.py

was causing tests to fail 
it is that kind of releases marathon ;-)

BF: add recently tests data missing from distribution

---

heudiconv/heuristics/reproin.py
heudiconv/heuristics/test_reproin.py

Should have no effect on functionality.

Minor face-lifts to ReproIn: align doc and code better to BIDS terms, address deprecation warnings etc

---

.readthedocs.yaml
README.rst
docs/changes.rst
docs/conf.py
docs/requirements.txt
heudiconv/bids.py
heudiconv/convert.py
heudiconv/parser.py
heudiconv/tests/test_bids.py
heudiconv/utils.py

Starting with Sphinx version 5.0, the configuration for the doc's language should not be None anymore and causes docbuild failures otherwise.
Might add other fixes to get RTD build docs again (see #603), I enabled preview on PRs, let's see ...
edit: introduced various other fixes to docstrings and sphinx configuration to make it build again .
Closes #603 (thanks @wasciutto  for reporting) and I will tag this PR for release so hopefully RTD gets it all nice and "modern" ;)

DOC: Various fixes to make RTD build the docs again

---

heudiconv/bids.py
heudiconv/convert.py
heudiconv/tests/test_main.py

Closes #132 as we already have duecredit added, and just forgot to credit dcm2niix for all its hard work

Duecredit dcm2niix

---

README.rst

@yarikoptic  Since we now have it on more than one distro :3

Added distribution badges

---

docs/heuristics.rst
docs/installation.rst

@mih or @satra might remember what that 3rd argument on `annotation_classes` is about.  Ref: #497

Clarify the infotodict function

---

.github/workflows/test.yml
docs/installation.rst
heudiconv/dicoms.py
heudiconv/info.py
utils/gen-docker-image.sh

Re-add explicit instructions to install dcm2niix "manually" and remove it from install_requires

---

docs/heuristics.rst

Inspired (and found to be missing in the docs) by https://github.com/nipy/heudiconv-joss-paper/pull/31/files#diff-0403ef06adf405f7b310b4518bd6a3559854f54c61676f676ce9cbfee7172ab6R173

Add description of placeholders which could be used in the produced templates

---

tox.ini

But really just to cut a release.

Add codespell to lint tox env

---

Makefile

No need to specify user for podman run as non-root

---

.github/workflows/release.yml

was missed in review of 
- #743

Fix - auto is in ~/, not in the PATH

---

paper.md

This PR fixes an error in the paper's metadata. 
Re: https://github.com/openjournals/joss-reviews/issues/5839

Fix metadata key

---

README.rst

DOC: Replace gone pointer to "Usage" with "CLI Reference"

---

.codespellrc
README.rst

Minor non-consecuential changes (trailing ., add venv folders to ignore for codespell)

---

.github/workflows/test.yml

This reverts commit 9d481a6f26804e15a637a9c55f968b8c1463a054.

Enable testing 3.13
